/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication4;

import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Abhi
 * 
 * 
 */


public class DoctorDesk extends javax.swing.JFrame {

    /**
     * Creates new form DoctorDesk
     */
public DoctorDesk(String uname){
    
    initComponents();
    show_user(uname);
    
}

    private DoctorDesk() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
    public void close(){
WindowEvent winClosingEvent=new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosingEvent);

}
    
   public ArrayList<User> userList(String uname) {
        ArrayList<User> userList=new ArrayList<>();
        try{  
Class.forName("com.mysql.jdbc.Driver");  

Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/project","root","root");
//here sonoo is database name, root is username and password) {
               
              
                String namer="";
                Statement stmt2=con.createStatement();
                
                String s="select name from doctors_list where id="+uname;
                ResultSet rs2=stmt2.executeQuery(s);
                 ArrayList < String > list = new ArrayList < String > ();
                   while (rs2.next()) {
                 namer=rs2.getString(1);
                   }
        
                jLabel6.setText(namer);
                Statement stmt=con.createStatement();
                String p="select * from "+namer;
                ResultSet rs=stmt.executeQuery(p);
                
                User user;
                while(rs.next())
                {
                    user=new User(rs.getString("patient_name"),rs.getString("sex"),rs.getString("address"),rs.getString("city"),rs.getString("date"));
                   userList.add(user);
                }
            }   
                catch( ClassNotFoundException | SQLException e){ System.out.println(e);}
        return userList;
                
                
        }

   public void show_user(String uname){
       ArrayList<User> list = userList(uname);
       jLabel5.setText(uname);
       DefaultTableModel model=(DefaultTableModel)jTable_Display_User.getModel();
   Object[] row=new Object[6];
  for(int i=0;i<list.size();i++){
      row[0]=list.get(i).getname();
      row[1]=list.get(i).getsex();
      row[2]=list.get(i).getaddress();
      row[3]=list.get(i).getcity();
      row[4]=list.get(i).getdate();
      model.addRow(row);
   }

   }
        
  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable_Display_User = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBounds(new java.awt.Rectangle(400, 120, 120, 120));
        setMinimumSize(new java.awt.Dimension(550, 450));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel3.setText("Hello Doctor");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(200, 30, 150, 14);

        jLabel4.setText("These Are your appointments::");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(10, 62, 310, 14);

        jTable_Display_User.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Patient Name", "Sex", "City", "Address", "Date"
            }
        ));
        jScrollPane2.setViewportView(jTable_Display_User);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(10, 80, 510, 260);

        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(858, 94, 34, 14);
        getContentPane().add(jLabel2);
        jLabel2.setBounds(482, 30, 0, 0);
        getContentPane().add(jLabel5);
        jLabel5.setBounds(280, 30, 0, 0);

        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(10, 556, 55, 23);

        jButton3.setText("Back");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(10, 370, 55, 23);

        jLabel6.setText("jLabel6");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(410, 40, 34, 14);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
      close();
      DoctorSignin r=new DoctorSignin();
      r.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        close();
        DoctorSignin r=new DoctorSignin();
        r.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    
   public static void main(String args[]) {
        /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DoctorDesk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DoctorDesk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DoctorDesk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DoctorDesk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DoctorDesk().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable_Display_User;
    // End of variables declaration//GEN-END:variables
}
